name: Deploy on ec2
on: [push]

jobs:
    build:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
        - name: Connect to SSH and deploy
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            key: ${{ secrets.SSH_KEY }}
            script: | 
                /home/${{ secrets.SSH_USERNAME }}/deploy.sh