name: SSH Remote Connection
on: [push]

jobs:
    build:
        name: Check SSH connection
        runs-on: ubuntu-latest
        steps:
        - name: SSH check
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            key: ${{ secrets.SSH_KEY }}
            script: | 
                whoami    